version: "3"
services:
    kalitass-api:
        build:
            context: .
            dockerfile: .docker/Dockerfile
        image: kalitass-api
        container_name: kalitass-api
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - ./:/var/www/html
        networks:
            - kalitass-api
        depends_on:
            - kalitass-api-pgsql

    kalitass-api-pgsql:
        restart: always
        image: 'postgres:13'
        ports:
            - '${FORWARD_DB_PORT:-5432}:5432'
        container_name: kalitass-api-pgsql
        environment:
            PGPASSWORD: '${PG_PASSWORD:-secret}'
            POSTGRES_DB: '${DB_DATABASE}'
            POSTGRES_USER: '${DB_USERNAME}'
            POSTGRES_PASSWORD: '${DB_PASSWORD:-secret}'
        volumes:
            - 'db-pgsql:/var/lib/postgresql/data'
        networks:
            - kalitass-api
        healthcheck:
            test: ["CMD", "pg_isready", "-q", "-d", "${DB_DATABASE}", "-U", "${DB_USERNAME}"]
            retries: 3
            timeout: 5s
networks:
    kalitass-api:
        driver: bridge
volumes:
    db-pgsql:
        driver: local
